### PR TITLE
Parse CLI arguments using `ketopt`

### PR DESCRIPTION
**Pull request by vladimyr**
Introduces [`klib`](https://github.com/attractivechaos/klib) dependency. (Only the `ketopt.h` file.)

Adding support for both long and short flags `-h` and `--help`.
This is the first step towards implementing #11

### CODE REVIEW

**Comment by avivbeeri** [comment]
If we just need to parse a few arguments, this might be overkill. Especially since we aren't using all of the `klib` includes. I feel like that bulk is unnecessary.

**Comment by vladimyr** [comment]
> If we just need to parse a few arguments, this might be overkill. Especially since we aren't using all of the `klib` includes. I feel like that bulk is unnecessary.

Ok, how about adding just `ketopt.h`?

**Comment by ruby0x1** [comment]
yea we don't want this kind of dependency. I have an option parser for c that I like that behaves like getopt_long but is portable, i'll take a closer look soon to decide if need a parser or just keep it simple.

**Comment by vladimyr** [comment]
https://attractivechaos.wordpress.com/2018/08/31/a-survey-of-argument-parsing-libraries-in-c-c/

**Comment by vladimyr** [comment]
> Thanks for the PR, but yea we don't want this kind of dependency. I have an option parser for c that I like that behaves like getopt_long but is portable, I'll take a closer look soon to decide if we need a parser or just keep it simple.

Let's pause and analyze things a bit. That _kind of dependency_ costs you exactly 3.9kb and 120 lines of pure ANSI c code. If that is not dependency one could wish for than we clearly have very different standards.
**Also `ketopt` is as portable as it gets. It depends on `string.h`, solely.**

You might have your own solution that you prefer and it is, of course, your choice to make. Thus I'll patiently wait till you prove to me it has all the flexibility `ketopt` gives you (listed in that blog post) plus all edge case handling plus portability plus minuscule size plus whole community behind it, plus you get the picture...

Also by rejecting this, you rejected the implementation of short flags for existing options which is quite unfortunate cause not supporting at least '-h' goes against typical user's expectations.

All in all, I pushed for this so I can move to `-e, --eval` and later on to `-l, --load` for module preloading (supporting multiple files) but as it seems that is now, unfortunately, off the table...

**Pull request closed without merging**
