### PR TITLE
Improve file/directory utils

### LINKED ISSUE #87: [RFC] Scheduler.await
I already spotted the call extern/Scheduler.runNextScheduled_() pattern:

```cpp
  static mkdir(path) {
     ensurePath_(path)
     mkdir_(path, Fiber.current)
     return Scheduler.runNextScheduled_()
     return await { mkdir_(path, Fiber.current) }
   }
```

And was replacing it with:

```js
  static mkdir(path) {
     ensurePath_(path)
     return await_ { mkdir_(path, Fiber.current) }
   }
```

But much like #65 it why don't we just move this responsibility into `Scheduler`:

```js
  static mkdir(path) {
     ensurePath_(path)
     return Scheduler.await_ { mkdir_(path, Fiber.current) }
   }
```

`await` is no doubt familiar to those doing async in JavaScript, but open to a better name...

### PR DESCRIPTION
**Pull request by joshgoebel**
- add Directory.create/remove
- added `Scheduler.await` abstraction around all the callbacks
- check return values for `scandir` and `unlink`

Resolves #87.

### CODE REVIEW

**Comment by Orcolom** [comment]
Wren prefers to be readable. `Directory.rmDir()` should thus be more along the lines of `Directory.remove()`. likewise for `mkDir`

**Comment by ruby0x1** [comment]
Thanks @Orcolom, also note that applies to the internal C code as well, it should be named clearly and consistently with the wren side as much as possible.

**Comment by joshgoebel** [comment]
>  it should be named clearly and consistently with the wren side as much as possible.

I actually found value in the distinction, but I can update this so that both sides match.

**Comment by joshgoebel** [comment]
Updating naming and moved `await` into scheduler.

**Comment by ChayimFriedman2** [comment]
I think we should name it `await_` as it's not public.

**Comment by joshgoebel** [comment]
I'm not sure it shouldn't or couldn't be public... it's a quite useful pattern, but then we'd technically need to document it and explain how to use it, etc... so I'm fine with making it private. :-)

**Comment by ChayimFriedman2** [comment]
No it's not, since `Scheduler.runNextScheduled_()` is not public either, and not meant for public use (though it'll be useful for plugins - that's one of their difficulties).

**Comment by joshgoebel** [comment]
Your right.  It's a useful _pattern_ (really Fibers in general), but we don't provide enough infrastructure to use it as-is.  Made private. :)

**Comment by ChayimFriedman2** [comment]
`Scheduler` as-is is not enough. I look for a way to provide some more methods, that will complete the async story:

 - `all(fibers)` to run a list of fibers in parallel and get all of their results.
 - `any(fibers)` to run a list of fibers in parallel and get the first successful result.

And probably other utilities to deal with combinations of successes/failures, though any utility can be created using the above one, by converting a failure to a success:
```wren
class AlwaysSuccessFiber {
  static fromFiber(fiber) { fromFiber(fiber, null) }
  construct fromFiber(fiber, arg) {
    _result = fiber.try(arg)
    _hadError = fiber.error != null
  }
  hadError { _hadError }
  error { _result }
  value { _result }
}
```

I struggle with implementing those, but I'm sure I'll find a way.

**Comment by joshgoebel** [comment]
Might be worth discussing in #93.  This isn't the best thread for "all things Scheduler". :-)

Full promises support sounds like something great for a library whether or not it's included in the CLI libs by default to not.

**Comment by ruby0x1** [comment]
Thanks for the PR, seems good with the consistency now.

**Comment by joshgoebel** [comment]
Great. Thank you!

**Pull request merged**
