### PR TITLE
(chore) Finish the Scheduler.await_ work

### PR DESCRIPTION
**Pull request by joshgoebel**
Follows up on #84.

Uses the new `Scheduler.await_` in the few places I missed previously
either because I glossed over them or because they were slightly more
complex. This should be fairly uncontroversial because it's just finishing
the work already started in #84.

The final places the new API has been used:

- `File.openWithFlags`
- `File.close`
- `Stat.path`
- `Timer.sleep`

<del>Also adds a new API to File:

- <del>`File.isClosed`

---

**Justification for File.isClosed**

I found it clearer to write:

```js
 close() {
    if (isClosed) return
    return Scheduler.await_ { close_(Fiber.current) }
  }
```

Than:

```js
 close() {
    if (!isOpen) return
    return Scheduler.await_ { close_(Fiber.current) }
  }
```

I think the natural english without negation is much easier to read and that makes it worth having both these functions.

### CODE REVIEW

**Comment by joshgoebel** [comment]
https://github.com/wren-lang/wren/pull/992 hasn't been merged yet so I can update the docs there to add `isClosed` if that's agreed... I found it clearer to write:

```
 close() {
    if (isClosed) return
    return Scheduler.await_ { close_(Fiber.current) }
  }
```

Than:

```
 close() {
    if (!isOpen) return
    return Scheduler.await_ { close_(Fiber.current) }
  }
```

I think the natural english without negation is much easier to read and that makes it worth having both these functions.

**Comment by ruby0x1** [comment]
I don't think we want to be duplicating API endpoints unnecessarily, multiple ways to do the same thing isn't usually good unless there's a strong reason. If we wanted it to be `isClosed` I think we would remove `isOpen`.

This particular case will come up in reverse though. If you want to check if the file is open, `!isClosed` will have the same problem. That makes neither better than the other. 

Except for the breaking change, in which case we'll keep `isOpen` and live with `!isOpen`, or use the clearer `isOpen == false` instead for clarity. I don't find that particularly unclear or less natural.

Given that it's one expression in one place it's not a particularly compelling reason to break the API or add duplicate functionality, so to move forward I'd revert it or use `isOpen == false` for that line.

**Comment by joshgoebel** [comment]
>  isn't usually good unless there's a strong reason.

Readability is a strong reason. :-)  I feel like I've seen (and written) other APIs that do this exact thing (two methods for the same piece of state) - and users use the one that best expresses their intention at the call site - the one that is most readable.  But we can agree to disagree on API design. :-)

> isOpen == false

Agree that this is definitely better than `!isOpen`.  I will update the PR accordingly.

**Comment by ruby0x1** [comment]
Readability is important, but as with all things there are trade offs and balance. Thanks for the PR!

**Pull request merged**
